# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #   Construction of main widget
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 525)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #   Construction of Name label, displays the program name
        self.Main_label = QtWidgets.QLabel(self.centralwidget)
        self.Main_label.setGeometry(QtCore.QRect(0, 0, 501, 41))
        self.Main_label.setStyleSheet("margin: 10;")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_label.sizePolicy().hasHeightForWidth())
        self.Main_label.setSizePolicy(sizePolicy)
        self.Main_label.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Main_label.setFont(font)
        self.Main_label.setObjectName("Main_label")

        #   Construction of Audio only checkbox
        self.Audio_box = QtWidgets.QCheckBox(self.centralwidget)
        self.Audio_box.setGeometry(QtCore.QRect(390, 100, 101, 21))
        self.Audio_box.setObjectName("Audio_box")

        #   Construction of separation line
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 200, 501, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        #   Construction of Download button
        self.Download_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Download_btn.setGeometry(QtCore.QRect(370, 170, 121, 31))
        self.Download_btn.setObjectName("Download_btn")

        #   Construction of channel export button
        self.Channel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Channel_btn.setGeometry(QtCore.QRect(0, 170, 161, 31))
        self.Channel_btn.setObjectName("Channel_btn")

        #   Construction of container for queue
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 220, 481, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        #   Construction of input area
        self.URL_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.URL_inp.setGeometry(QtCore.QRect(0, 40, 501, 61))
        self.URL_inp.setStyleSheet("margin: 10;")
        self.URL_inp.setObjectName("URL_inp")

        #   Construction of Save to widget
        self.Saveto_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Saveto_lbl.setGeometry(QtCore.QRect(10, 120, 121, 31))
        self.Saveto_lbl.setObjectName("Saveto_lbl")

        #   Construction of path widget, displays path to save videos
        self.path_lbl = QtWidgets.QLabel(self.centralwidget)
        self.path_lbl.setGeometry(QtCore.QRect(140, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_lbl.setFont(font)
        self.path_lbl.setObjectName("path_lbl")

        #   Construction of browse button
        self.Browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_btn.setGeometry(QtCore.QRect(310, 125, 111, 23))
        self.Browse_btn.setObjectName("Browse_btn")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YT-Downloader"))
        self.Main_label.setText(_translate("MainWindow", "YT-Downloader"))
        self.Audio_box.setText(_translate("MainWindow", "Audio only"))
        self.Download_btn.setText(_translate("MainWindow", "Download"))
        self.Channel_btn.setText(_translate("MainWindow", "Channel export"))
        self.URL_inp.setPlaceholderText(_translate("MainWindow", "Video or Playlist or Channel URL here"))
        self.Saveto_lbl.setText(_translate("MainWindow", "Will be saved to:"))
        self.path_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.Browse_btn.setText(_translate("MainWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
